version: '3'

services:
  posters:
    image: idotta/posters-app
    build: .
    ports:
      - 3000:3000
    restart: always
    links: 
      - db
    depends_on: 
      - db
    volumes:
      - ./:/usr/src/app
      - postersdata:/usr/src/app/node_modules
      - postersdata:/usr/src/app/public
      #- postersdata:/usr/src/app/uploads

  db:
    image: mongo:3.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: posters
    volumes:
      - mongodata:/data/db
      - mongodata:/var/lib/mongodb
      - mongodata:/var/log/mongodb

volumes:
  postersdata: {}
  mongodata: {}