version: '3'

services:
  posters:
    image: idotta/posters-app
    build: .
    ports:
      - 3000:3000
    restart: always
    links: 
      - mongo
      - redis
    depends_on: 
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - postersdata:/usr/src/app/node_modules
      - postersdata:/usr/src/app/public
      #- postersdata:/usr/src/app/uploads
    environment:
      MONGODB_URI: mongo:27017
      REDIS_STORE_URI: redis://localhost
      REDIS_STORE_SECRET: littlesecret

  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: posters
    volumes:
      - mongodata:/data/db
      - mongodata:/var/lib/mongodb
      - mongodata:/var/log/mongodb

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  postersdata: {}
  mongodata: {}
  redisdata: {}